## Data science bootcamp - Week 2 - Navdeep Mugathihalli Kumaregowda - nm4686

## HW Questions (Numpy):

### 1.Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

print("Array A:\n", A)
print("\nArray B:\n", B)


vertical_stack = np.vstack((A, B))

print("\n Vertically Stacked Array (A on top of B) ")
print(vertical_stack)


horizontal_stack = np.hstack((A, B))

print("\n Horizontally Stacked Array (A next to B) ")
print(horizontal_stack)

Array A:
 [[1 2 3]
 [4 5 6]]

Array B:
 [[ 7  8  9]
 [10 11 12]]

 Vertically Stacked Array (A on top of B) 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 Horizontally Stacked Array (A next to B) 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 2.Find common elements between A and B. [Hint : Intersection of two sets]

In [4]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[5, 6, 7],
              [8, 9, 10]])


common_elements = np.intersect1d(A, B)


print(f"\nCommon elements between A and B: {common_elements}")


Common elements between A and B: [5 6]


### 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks

In [6]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])


mask = (A >= 5) & (A <= 10)

print("Boolean Mask")
print(mask)


result = A[mask]

print("\n Numbers in A between 5 and 10 ")
print(result)

Boolean Mask
[[False False False]
 [False  True  True]]

 Numbers in A between 5 and 10 
[5 6]


### 4.Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3]

In [7]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [8]:
mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)

filtered_iris = iris_2d[mask]

print(" Filtered Iris Data ")
print(filtered_iris)

 Filtered Iris Data 
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## HW Questions (Pandas):

### 1.From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [9]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')


result = df.iloc[::20, [0, 1, 2]]

print(result)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


### 2.Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [12]:
import pandas as pd

url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)


print(" Missing Values Before ")
print(df[['Min.Price', 'Max.Price']].isnull().sum())

 Missing Values Before 
Min.Price    7
Max.Price    5
dtype: int64


In [13]:
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

fill_values = {'Min.Price': min_price_mean, 'Max.Price': max_price_mean}


df.fillna(value=fill_values, inplace=True)

print("\n Missing Values After ")
print(df[['Min.Price', 'Max.Price']].isnull().sum())


 Missing Values After 
Min.Price    0
Max.Price    0
dtype: int64


### 3.How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [14]:
import pandas as pd
import numpy as np


df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(" Original DataFrame ")
print(df)

 Original DataFrame 
     0   1   2   3
0   12  26  24  19
1   30  35  31  39
2   33  13  34  26
3   12  35  31  15
4   24  22  35  20
5   28  23  19  25
6   33  36  27  23
7   15  34  12  11
8   16  21  13  24
9   34  35  22  31
10  10  24  10  20
11  32  16  12  32
12  12  13  18  20
13  14  39  11  11
14  20  12  12  28


In [16]:
row_sums = df.sum(axis=1)

filtered_df = df[row_sums > 100]

print("\n Filtered DataFrame (Row Sum > 100) ")
print(filtered_df)


 Filtered DataFrame (Row Sum > 100) 
    0   1   2   3
1  30  35  31  39
2  33  13  34  26
4  24  22  35  20
6  33  36  27  23
9  34  35  22  31
